https:
  host: "0.0.0.0"
  port: "8081"
  readTimeout: "30000"


api:
  autodiscovery: "19496659"
  version: "v1"


endSystem:
  PW-CIN7-PROC:
    protocol: "https"
    host: "pw-cin7-prc-api-dev-o4o3m1.5sc6y6-2.usa-e2.cloudhub.io"  
    client_id: "![V/IFXu3qOniFumDV7Xy3Q7/3mUfmRnfIm5DAAgm0yCybiQeKOJKlpg==]"
    client_secret: "![Z+DnxnnqhhJLgjvsIu4CwTjf5KknJoRHEKlwpRtp8hQjjd73tuM++w==]"
    response:
      timeout: "50000"
      
  CIN7:
    protocol: "https"
    host: "inventory.dearsystems.com"  
    response:
      timeout: "50000"
      
  cin7-sys-api:
    host: "pw-cin7-sys-api-dev-o4o3m1.5sc6y6-2.usa-e2.cloudhub.io"
    port: ""
    protocol: "HTTPS"
    client_id: "![V/IFXu3qOniFumDV7Xy3Q7/3mUfmRnfIm5DAAgm0yCybiQeKOJKlpg==]"
    client_secret: "![Z+DnxnnqhhJLgjvsIu4CwTjf5KknJoRHEKlwpRtp8hQjjd73tuM++w==]"
 
          

operation:
  CUSTOMER:
    path: "/api/customers"
    method: 'POST'
    
  PRODUCT:
    path: "/api/products"
    method: 'POST'
    
  STOCK:
    path: "/stock"
    method: 'POST'
    
  SALES-ORDER:
    path: "/api/salesOrders"
    method: 'POST'
    
  GET-LOCATION:
    path: "/api/locations"
    method: "GET"
    
  
sfdc:
  basepath: "/api/v1"
  host: "pw-sf-sys-api-dev-o4o3m1.5sc6y6-2.usa-e2.cloudhub.io"
  port: ""
  client-id: "![dSnqtH73b+K9XWFeVWquErgXi9NQsw1cBCJsHBG+sf9d1/QugFivAQ==]"
  client-secret: "![KcmRb2Ji/e7M+J0aZHTssR59lPrjftCgPfgNeAxP3aQ80HuYTwF5mg==]"
  upsert: "/upsert"
  query: "/query"
  
request:
  response:
    values: '0..599'
  
email:
  host: "smtp.gmail.com"
  port: "587"
  from: "james@principalwine.com.au"
  recipients: "divyansh.r.kumar@apisero.com, sameet.bhole@apisero.com, prabhat.kumar@apisero.com"
  password: "![bJQhTx9JApX86gnBXmpZTqLBji1Q9+LS]"