https:
  host: "0.0.0.0"
  port: "8081"
  readTimeout: "30000"


api:
  autodiscovery: ""
  
pwCin7Proc:
  host: "inventory.dearsystems.com"
  protocol: "HTTPS"
  port: "443"
  basePath: "/api"
  maxConnections: "100"
  idleTimeout: "30000"
  responseTimeout: "60000"
  reconnection:
    frequency: "3000"
    attempts: "3"

endSystem:
  PW-CIN7-PROC:
    protocol: "https"
    host: "inventory.dearsystems.com"  
    response:
      timeout: "50000"
          

operation:
  CUSTOMER:
    path: "/customer"
    method: 'POST'
    
  PRODUCT:
    path: "/product"
    method: 'POST'
    
  STOCK:
    path: "/stock"
    method: 'POST'
    
  SALES-ORDER:
    path: "/salesOrder"
    method: 'POST'
    
PW-CIN7-PROC-SECURE:
  client_id: "![1F+4hnZf0/c+cT73EgH5G1f2KAGGVv3tfnEgE9y6Oclfsmnse5rwdg==]"
  client_secret: "![ar4oGs1A/tSmjWqs4V7AXPailP7XiHLGmId/p+EfeurfXt0+DA98Yw==]"
    
    
  
    
  
